#%RAML 0.8
title: Simple restaurant
version: 1
baseUri: http://restaurant-api.devcharles.com
mediaType: application/json
documentation:
  - title: Description
    content: !include documentation.md

/orders: !include orders/orders.raml

/dishes: !include dishes/dishes.raml




