get:
  description: List all existing dishes
post:
  description: Add more dishes
/{id}:
  get:
    description: Get the deatil information of a dish
  put:
    description: Update a dish specs
  delete:
    description: Delete a dish
