get:
  description: List all existing dishes
  responses:
    200:
      description: List of dishes retrieved successfully
      body:
        example: !include get-200-resp-example.json
  
post:
  description: Add more dishes 
  body:
    example: !include post-req-example.json
  responses:
      200:
        description: Dish created successfully
        body:
          example: !include post-200-resp-example.json
  