#%RAML 0.8
get:
  description: List all the orders
post:
  description: Create a new order
/{id}:
  get:
    description: Get information about the order
  put:
    description: Update order information
  delete:
    description: Delete an order
